// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyC-l9iziNIRpUE2HA0OOng9KQ8hz0LUcQg",
    authDomain: "directory-app-2c683.firebaseapp.com",
    projectId: "directory-app-2c683",
    storageBucket: "directory-app-2c683.appspot.com",
    messagingSenderId: "135527654970",
    appId: "1:135527654970:web:5fe030e0e6a10fbbc47703",
    measurementId: "G-XKW2Z8B3TV"



  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBU8rU_-J2BTzcAibyVevJ0GtAi_C6RlQ',
    appId: '1:135527654970:android:c009246ab882f8aec47703',
    messagingSenderId: '135527654970',
    projectId: "directory-app-2c683",
    storageBucket: 'directory-app-2c683.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY7VgmbjZn2KCXUh_PWNfPBe2qt5WU2k0',
    appId: '1:782813816644:ios:b2cc83000747cfc91b1911',
    messagingSenderId: '782813816644',
    projectId: 'brain-sugar',
    storageBucket: 'brain-sugar.appspot.com',
    iosBundleId: 'com.directory.sau',
  );
}
