// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZp12IY9BafrRwks-W_6zHObDZWk9iQjI',
    appId: '1:782813816644:web:00b77e0c6a4ea1191b1911',
    messagingSenderId: '782813816644',
    projectId: 'brain-sugar',
    authDomain: 'brain-sugar.firebaseapp.com',
    storageBucket: 'brain-sugar.appspot.com',
    measurementId: 'G-3L9ERG0K95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe3a3F55CuEemejGG1aX_-f9QoPuDLNpw',
    appId: '1:782813816644:android:703d4adb8e2e055f1b1911',
    messagingSenderId: '782813816644',
    projectId: 'brain-sugar',
    storageBucket: 'brain-sugar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY7VgmbjZn2KCXUh_PWNfPBe2qt5WU2k0',
    appId: '1:782813816644:ios:b2cc83000747cfc91b1911',
    messagingSenderId: '782813816644',
    projectId: 'brain-sugar',
    storageBucket: 'brain-sugar.appspot.com',
    iosBundleId: 'com.directory.sau',
  );
}
